server:
  port: 8080
  error:
    include-details: always
    
#Base de datos
spring:
  datasource:
    url: jdbc:mysql://mysqldb/exchangeratedb
    #url: jdbc:mysql://localhost:3306/exchangeratedb?serverTimezone=GMT-6
    username: root
    password: root
    #password: 123456
    platform: mysql
    initialization-mode: always
    #driver-class-name: com.mysql.cj.jdbc.Driver

#Ouath2 Service
signing:
    key: "345345fsdfsf5345"

security:
    oauth2:
        resource:
            userInfoUri: http://ms-authentication:8886/user
            #userInfoUri: http://localhost:8886/user