version: '3'
services:
  #name image
  exchange-rate:
    image: exchange-rate:latest
    ports:
      - 33002:8000
      - 32002:8080
      - 34002:9010
    networks:
      - network-mysql
      - network-services
    depends_on:
      - mysqldb
      #extra_hosts:
      #- "domain-host:192.168.100.192"
    environment:
      - JAVA_OPTS=-Xmx256m
      - PROFILING=-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false
  mysqldb:
    image: mysql:8
    command: --lower_case_table_names=1
    networks:
      - network-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=exchangeratedb
  
#
# [ networks definition ]
#
networks:
  network-mysql:
    driver: bridge
    external: true
  network-services:
    external: true
    
  